### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by MercerK** [SuperGoatLand/sgl-wiki#3]
# Host Server

* [x] Backup contents
* [x] Update host server
  - OS Update
  - App Updates
* [x] Update Discord bot host server
* [x] Update Pterodactyl Panel
* [x] Update Pterodactyl Wing

# 1.17 Preparation

* [x] Update plugins again
* [x] Purge chunks (1hr)
* [x] Purge nether chunks (5m)
* [x] Custom purge end chunks
* [x] Merge worlds

# Pterodactyl

* [ ] Remove TempSpawn server
* [ ] Create new server to replace old server

# Plugins
* [ ] Update Supervanish
* [ ] Update Essentials again

# 1.17.0 Checklist

* [x] Fix lands bluemap integration
* [x] Fix lands config
* [x] Update MOTD
* [x] Clear deaths challenge
* [x] Use tab counter on challenge
* [x] New Challenge
* [x] Set spawn protections
* [x] Set spawn point
* [x] Create portals connecting spawns
* [x] Create portals connecting nether
* [x] Create Warp to Spawn
* [x] Set spawnpoint to new spawn
* [x] Set /spawn to new spawn
* [x] Update home to 2
* [x] Add ViaBackwards (for 1.16.5 players)
* [x] Disable mob spawning for spawn
* [x] Update xray anti-cheat
* [x] Lands Wild command
* [x] Update Marketplace to diff. name 

# Post 

* [ ] Rework backups
* [ ] Fix color signs for staff
* [ ] Look into worldguard and why owners/members can't build?
* [ ] Fix old marketplace's flags

**Comment by MercerK** [comment]
* Server got corrupted on the final save/backup.
* Pterodactyl changed wings configs (for some reason).

**Comment by MercerK** [comment]
# Announcement

Server has been updated to 1.17. See below for changes:

1. Refer to [MC 1.17](https://www.minecraft.net/en-us/article/caves---cliffs--part-i-out-today-java).
2. Any chunks that have 1 hour or less playtime in the Overworld have been purged.
3. Any chunks that have 5 minutes or less playtime in the Nether have been purged.
4. The "Goat Ender" is now the connected end. 
5. The outskirts of the "Goat Ender" have been purged, except for known player content (Pixel's Wither).
6. The main island have been purged, except for player content (The primary Enderman farm).
7. Brand new spawn, thanks to @Galaxy.
8. Additional homes. Players will now have 2 homes, versus 1. This is to allow players to create a new home in 1.17 chunks.
9. Warp command to spawn. 
10. Dynmap has been replaced with Bluemap. Go check it out at map.supergoat.land. 
11. Death challenge reset back to 0 for all players.
12. 

Please note, some things are temporarily disabled:

1. Zombie Flesh Gambling
2. Custom Recipes, such as:
  - Diamond Nugget
  - Slabs to Planks
  - Etc
3. Disguises

**Comment by MercerK** [comment]
Copper ore challenge (no deepslate)

**Comment by MercerK** [comment]
Add shopkeeper changes

**Comment by MercerK** [comment]
Lands made changes to their config, which added a default expiration, resulting in an automatic purge of a lot of lands. Had to restore from a plugin.

**Comment by MercerK** [comment]
There is now a 6 month expiration for lands.

**Comment by MercerK** [comment]
Townhall somehow had a chunk corruption.

**Comment by MercerK** [comment]
readd build permission for spawn portal room
